// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = "NTIG Guest";    // Network SSID (name)
const char PASS[]     = "TeknikPassion";    // Network password (use for WPA, or use as key for WEP)


float humidity;
float pressure;
float tempBMP;
float tempDHT;

void initProperties(){

  ArduinoCloud.addProperty(humidity, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(pressure, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(tempBMP, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(tempDHT, READ, ON_CHANGE, NULL);



}

WiFiConnectionHandler ArduinoIoTPreferredConnection("NTIG Guest", "TeknikPassion");
